[package]
name = "dogsense"
version = "0.1.0"
authors = ["Morten Dahl <mortendahlcs@gmail.com>"]

[dependencies]
sensehat = "0.4"
dogstatsd = { git = "https://github.com/mortendahl/dogstatsd-rs" }
chrono = "0.4"
timer = "0.1"
